# Copyright (C) 2018 Betalo AB - All Rights Reserved

[[constraint]]
  name = "go.uber.org/zap"
  revision = "f85c78b1dd998214c5f2138155b320a4a43fbe36"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
