# Copyright (C) 2018 Betalo AB - All Rights Reserved

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "go.uber.org/zap"
  version = "^v1.8"

[[constraint]]
  name = "golang.org/x/crypto"  # For "golang.org/x/crypto/acme/autocert"
  revision = "0e37d006457bf46f9e6692014ba72ef82c33022c"  # arbitrary choice


# Test

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^v1.2"
